### ISSUE TITLE
User Stories 

### ISSUE THREAD

**Issue by mohammedmh** [FACG6/wallet#5]
**As a guest**
- [ ]  I can view the main page ( wallet ) without sign in to website 
- [ ] I can click plus icon to view the plan of the income.
- [ ] I can click on add button but I will get a message to log in or sign up to the website
- [ ] I can create new account
- [ ] I can login to my wallet in the website

**As a user**
- [ ] I can view my may wallet page
- [ ] I can click on the plus icon to view the plan page
- [ ] I can add my income with the period selected, select the categories and add expected budget for each one
- [ ] I can view my plan in my wallet page
- [ ] I can click on the plus icon for specific category and view add expenses pop up
- [ ] I can add my expenses ( price, date, description )
- [ ] I can see all changes in total expenses and expenses for updated category
- [ ] I can view all my transaction
- [ ] I can view all transaction for specific category
- [ ] I can delete specific expenses from specific category
- [ ] I can log out from my wallet
